# Generated by Django 2.1.2 on 2018-10-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_connect', '0006_auto_20181030_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
