# Generated by Django 2.1.2 on 2018-10-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_connect', '0003_auto_20181029_2225'),
        ('dev_connect', '0007_auto_20181030_2119'),
    ]

    operations = [
    ]
