# Generated by Django 2.1.2 on 2018-10-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_connect', '0008_merge_20181031_1840'),
        ('dev_connect', '0008_merge_20181031_1739'),
        ('dev_connect', '0008_merge_20181031_1849'),
    ]

    operations = [
    ]
